### ISSUE TITLE
.Net 6.0 Support

### ISSUE THREAD

**Issue by ONYXDave** [Data8/DataverseClient#1]
Is there any plans on making this usable in a .Net 6 application?

**Comment by MarkMpn** [comment]
This package works in my test .NET 6 apps. Are you getting any particular errors?

**Comment by ONYXDave** [comment]
I am not sure if it something I am doing wrong then but I get Unable to cast object of type 'Microsoft.Xrm.Sdk.Entity' to type 'Account' when trying it out on a simple test.

OnPremiseClient? service = new OnPremiseClient("https://url/orgname/XRMServices/2011/Organization.svc", "AD\\name", "password");
CrmContext? c = new CrmContext(service);


using (var ctx = new CrmContext(service))
{
    var a = ctx.AccountSet.First();
}

**Comment by MarkMpn** [comment]
I haven't attempted to add support for early bound classes - it currently only supports the late bound model.
