### ISSUE TITLE
Authenticate of ADAuthClient method is failing

### ISSUE THREAD

**Issue by vmcbaptista** [Data8/DataverseClient#10]
Hi. In the environment I'm using to test this client, Authenticate is crashing.
By looking into the code and the requests that were happening, I believe that this is occurring because the negotiation flow for issuing the token is not right.

WS-Trust specification says the following:
1.     A request is initiated with a <wst:RequestSecurityToken> that identifies the details of the request (and may contain initial negotiation/challenge information)
2.     A response is returned with a <wst:RequestSecurityTokenResponse> that contains additional negotiation/challenge information.  Optionally, this may return token information in the form of a <wst:RequestSecurityTokenResponseCollection> (if the exchange is two legs long).
3.     If the exchange is not complete, the requestor uses a <wst:RequestSecurityTokenResponse> that contains additional negotiation/challenge information.
4.     The process repeats at step 2 until the negotiation/challenge is complete (a token is returned or a Fault occurs). In the case where token information is returned in the final leg, it is returned in the form of a <wst:RequestSecurityTokenResponseCollection>.
https://docs.oasis-open.org/ws-sx/ws-trust/200512/ws-trust-1.3-os.html#_Toc162064978

This means that wst:RequestSecurityToken shall be sent only once, and wst:RequestSecurityTokenResponse shall be sent in a loop until we get the token.

So looking to the https://github.com/Data8/DataverseClient/blob/51e04e97ba74fd5e1fc242afe3fe3679039f5334/Data8.PowerPlatform.Dataverse.Client/ADAuthClient.cs#L113

I can see that the while loop can make wst:RequestSecurityToken to be sent more than once. This was what happened with me.

A possible way to fix this might be something like:

```
var rst = new RequestSecurityToken(token);
            var resp = rst.Execute(_url, auth);

            // Keep exchanging tokens until we get a full RSTR
            var finalResponse = resp as RequestSecurityTokenResponseCollection;
            while (finalResponse == null)
            {
                if (!(resp is RequestSecurityTokenResponse r)) throw new Exception("Did not get RequestSecurityTokenResponse as expected.");
                _context.Init(r.BinaryExchange.Token, out token);
                resp = new RequestSecurityTokenResponse(r.Context, token).Execute(_url, auth);
                finalResponse = resp as RequestSecurityTokenResponseCollection;
            }
```

What do you think about this?

**Comment by MarkMpn** [comment]
I agree with your diagnosis, but I've never seen this happen with any of the example instances I've used for testing. In my testing I've either seen a single leg (RST -> RSTRC) or two legs (RST -> RSTR -> RSTR -> RTRC). Both these are handled by the current code. I'm happy to make a change along the lines you suggest, but I'd like to see it failing in action to prove the change works. Do you have any details about how your instance is configured that might make it require an additional round trip, and/or a Fiddler log of a successful connection attempt from the old SDK?

**Comment by vmcbaptista** [comment]
> I agree with your diagnosis, but I've never seen this happen with any of the example instances I've used for testing. In my testing I've either seen a single leg (RST -> RSTRC) or two legs (RST -> RSTR -> RSTR -> RTRC). Both these are handled by the current code. I'm happy to make a change along the lines you suggest, but I'd like to see it failing in action to prove the change works. Do you have any details about how your instance is configured that might make it require an additional round trip, and/or a Fiddler log of a successful connection attempt from the old SDK?

Here you have 2 fiddler logs, the one named `old sdk` shows what happens when executing the constructor of `CrmServiceClient`.
The other file shows what happens when invoking the `OnPremiseClient` followed by an `Execute(new WhoAmIRequest())`

[fiddler.zip](https://github.com/Data8/DataverseClient/files/8548659/fiddler.zip)

I hope that it helps

**Comment by MarkMpn** [comment]
Thanks - still not sure how I can get my test servers to use that behaviour, but I can see it happening for you. Would you like to submit your proposed change as a PR?

**Comment by vmcbaptista** [comment]
Yes, I can make a PR, although the implementation I've proposed does not look into state returned by context.init. I actually do not know which condition shall I add to prevent infinite loop in case we never get a RTRC

**Comment by MarkMpn** [comment]
OK, I've just opened #14 which I believe should fix it, but I'm still setting up the tests. As I can't get my server to produce this extra leg of the authentication process, can you try running this modified code against your instance to see if that authenticates correctly?

**Comment by vmcbaptista** [comment]
I can confirm that your PR works with my instance.

BTW I've noticed that there is another thing that might break in some environments.
The Identity under EndpointReference contains only Upn. So, in instances configured with Spn instead of Upn, it will break.
I've also seen situations where Identity was not present inside EndpointReference (this is most probably some misconfiguration), nevertheless, I think the code here: https://github.com/Data8/DataverseClient/blob/623986dc51e1446f7f52b0100998aeb7e2e34458/Data8.PowerPlatform.Dataverse.Client/OnPremiseClient.cs#L122 could be improved to support Spn and EndpointReference without identity.

I think that the scenario without identity can be resolved to null, as the description for serverPrinc of ClientContext of SSPI says, "The principle name of the server to connect to, or *null* for any"

**Comment by MarkMpn** [comment]
So far I've been unable to replicate a situation where the WSDL doesn't include a UPN. Do you have any instructions you can share for me to set this test up?

**Comment by MarkMpn** [comment]
Can you check the latest code from #14 and see if that authenticates correctly against this instance please?

**Comment by vmcbaptista** [comment]
Yes #14 works fine 👍
