### ISSUE TITLE
Support .NET Standard

### ISSUE THREAD

**Issue by Misiu** [Data8/DataverseClient#11]
I have an old (legacy) project that is using .NET Framework 4.6.2 and Microsoft.CrmSdk.XrmTooling.CoreAssembly 9.1.0.86
I'd like to move my project to .NET 6, to do that I'd like to port my common code to .NET Standard 2.0 (because it supports .NET 4.62 and .NET 6).
I'd like to use your project, but it targets .NET Core 3.1.
Can it target .NET Standard 2.0?

**Comment by Misiu** [comment]
Or target multiple frameworks.
I was able to compile your library against `net462;net472;net48;netcoreapp3.1` ( same as dataverse NuGet).
https://github.com/Misiu/DataverseClient/commit/5aa29867ce4fcb123e058e45be07d3945d51181f

I can create PR if this is a feature you may consider adding.

**Comment by vmcbaptista** [comment]
This is something that might be useful for me as well.

**Comment by MarkMpn** [comment]
I don't believe the required APIs are available in .NET Standard 2.0, but I'd be happy to look at a PR for multi-targeting.

**Comment by Misiu** [comment]
@MarkMpn I'll create PR after some tests. My test app in .NET 6 works perfectly, but I must create a similar one in .NET Framework 4.6.2 and 4.8. I'll do that right away and create PR so we can start working on adding support for multiple targets.

**Comment by Misiu** [comment]
@MarkMpn - https://github.com/Data8/DataverseClient/pull/12
Reviews and comments are more than welcome :)

**Comment by Misiu** [comment]
@MarkMpn I can do an additional cleanup of the project when my first PR gets approved.
Some quick fixes Resharper suggested: https://github.com/Misiu/DataverseClient/commit/d48f2914869a56af120f43f38b2490165c5a0aa0

**Comment by MarkMpn** [comment]
Fixed in #12  - thanks!

**Comment by Misiu** [comment]
@MarkMpn what about cleanup? I can do that in the next PR.
ANy chance to release a new version with my changes?

**Comment by MarkMpn** [comment]
New version is building now, should be pushed to NuGet shortly.

I'm happy to review any other PRs, but I'm not a fan of accepting all Resharper suggestions without some thought. Each change should add some real value, in terms of readability, performance or correctness.

**Comment by Misiu** [comment]
@MarkMpn I agree with that. Resharper isn't perfect.
https://github.com/Data8/DataverseClient/pull/13

**Comment by Misiu** [comment]
> New version is building now, should be pushed to NuGet shortly.

A new version on NuGet is available, but Tag (https://github.com/Data8/DataverseClient/tags) is missing.
