### ISSUE TITLE
Virtualize OnPremiseClient

### ISSUE THREAD

**Issue by clintonbale** [Data8/DataverseClient#15]
Hoping that all the public methods exposed via the `IOrganizationService` interface in `OnPremiseClient` can be set to `public virtual`. This will enable logging, analytics, timing and modifications of CRM requests more easily, without having to use method hiding. (would much rather pass around an `IOrganizationService`)

**Comment by MarkMpn** [comment]
I wouldn't have a problem with this, do you want to submit that as a pull request?
