### ISSUE TITLE
Linux host support

### ISSUE THREAD

**Issue by Misiu** [Data8/DataverseClient#20]
I'm building a .NET 6.0 REST API that will allow querying Dynamics 365, API is containerized using Docker for Linux (mcr.microsoft.com/dotnet/aspnet:6.0).
Problem is that this awesome library supports only Windows.

Are there any plans to support Linux hosts?

**Comment by Misiu** [comment]
Sadly I have an environment that only supports Windows Authentication.
There is a plan to add IFD and ADFS, but that won't happen too soon.
I've tried to find any information about Win Auth for Linux in C#, but sadly nothing I can share could help with this issue.

From your experience, can Win Auth and IFD work together side-by-side?

**Comment by MarkMpn** [comment]
As far as I'm aware, enabling claims-based authentication (a pre-requisite to setting up IFD) disabled Windows authentication - I've never seen the two side-by-side.

I believe a Linux implementation of Windows authentication should be possible using GSSAPI, but I have no experience of that and I'd need someone who understands that area to build it.

**Comment by Misiu** [comment]
What about https://github.com/CoreWCF/CoreWCF? Maybe it could be used?
It was mentioned here: https://github.com/microsoft/PowerPlatform-DataverseServiceClient/issues/110#issuecomment-1216405925

**Comment by MarkMpn** [comment]
@Misiu I believe this only addresses the server-side components of WCF, not client-side. It looks like it might be possible using the new `System.Net.Security.NegotiateAuthentication`[https://github.com/dotnet/runtime/pull/70720] class in .NET 7 - I'll revisit this once .NET 7 is released.
