### ISSUE TITLE
.NET 4.6.2 notification

### ISSUE THREAD

**Issue by GitHubAssessments** [Data8/DataverseClient#21]
Hi,

I am receiving the warning below for this library:

"Msbuild failed when processing the file 'C:\Users(...)\Data8\DataverseClient-master\DataverseClient-master\Data8.PowerPlatform.Dataverse.Client\Data8.PowerPlatform.Dataverse.Client.csproj' with message:

C:\Program Files\dotnet\sdk\5.0.201\Microsoft.Common.CurrentVersion.targets: (1216, 5): The reference assemblies for .NETFramework,Version=v4.6.2 were not found.

To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks."

**Comment by MarkMpn** [comment]
Does it work if you install the developer pack as described in the error message?

**Comment by GitHubAssessments** [comment]
Hi, 
Yes. Thank you. Issue solved.
Kind Regards,
