### ISSUE TITLE
Missing license on the git repository

### ISSUE THREAD

**Issue by Finickyflame** [Data8/DataverseClient#23]
I would be interested to fork the repo but unfortunately there's no license on the repository.

However, there's the MIT license displayed on the [Nuget package](https://www.nuget.org/packages/Data8.PowerPlatform.Dataverse.Client#:~:text=Source%20repository-,MIT%20license,-Download%20package%20%C2%A0(232.96)), so should we also consider the repo to use the same license?

Thanks

**Comment by Misiu** [comment]
@MarkMpn can you add license information to this repo? We would have one issue less. Thank you 🙂

**Comment by Misiu** [comment]
@MarkMpn sorry for the second mention, but while listing requirements in my dev project I had to list libraries with versions and license information. As the author mentioned Nuget package has the MIT license, this repo should have the same license, so we can be 100% sure everything is okay.
