### ISSUE TITLE
Implement IOrganizationServiceAsync2

### ISSUE THREAD

**Issue by Misiu** [Data8/DataverseClient#25]
I'm trying to add DataverseClient to ASP.NET 7 Web API project, when following tutorials I noticed that there are Async operations in ServiceClient, but sadly they are missing in your library.
Take a look at this: https://taerimhan.com/implementing-oauth-2-0-on-behalf-of-flow-for-dataverse-custom-connector/

I noticed that ServiceClient implements an additional interface: https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/dd3a3893d135bcb8c023e9d700824f2effd28786/src/GeneralTools/DataverseClient/Client/ServiceClient.cs#L42

any chance it might get implemented?

**Comment by MarkMpn** [comment]
Yes, I'm working on this now.
