### ISSUE TITLE
No Clone method

### ISSUE THREAD

**Issue by Misiu** [Data8/DataverseClient#26]
I'm trying to add DataverseClient to an existing ASP.NET web API project.
I've migrated to .NET 7 RC2, added your library, and was able to do a basic query in the controller.
Now I'd like to optimize client creation by following the steps found here: https://colinvermander.wordpress.com/2020/03/26/cdsserviceclient-with-asp-net-core/
The basic idea is to add a single instance as a singleton, call Clone on that object, and add it as transient.
Ref: https://github.com/CdsWeb-app/CdsWeb/blob/master/src/CdsWeb/Extensions/CdsServiceClientExtensions.cs

Sadly there is no Clone method in OnPremiseClient like in ServiceClient (https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/dd3a3893d135bcb8c023e9d700824f2effd28786/src/GeneralTools/DataverseClient/Client/ServiceClient.cs#L1323).

I'd like to ask for implementing such feature and/or tips whats the best way to add OnPremiseClient to ASP.NET app to avoid new connections on each request.

**Comment by MarkMpn** [comment]
The Clone method in the standard client relies on using OAuth authentication. It doesn't work with using WS-Trust, which is what this library is designed to work with, so unfortunately you'll need to either create a new instance for each request or maintain a pool that you can reuse instances from.

**Comment by Misiu** [comment]
Thank you for such a quick reply. For now, I'm adding an instance as a transient scope, it works after some basic tests, and I'll try to run some tests that involve multiple parallel requests and we'll see what the results will look like.

**Comment by Misiu** [comment]
Hi Mark,
I want to return to this issue.
I have basic logic ready in my project, and after I enabled open telemetry I noticed that the library is doing two requests when the client instance is created (the logic is correct).

I'm adding client using this method:
```
services.AddTransient<IOrganizationServiceAsync2, OnPremiseClient>(sp =>
    {
        var options = sp.GetService<IOptions<DataverseServiceClientOptions>>();
        ArgumentNullException.ThrowIfNull(options?.Value);

        return new OnPremiseClient(options.Value.ConnectionString, options.Value.Username, options.Value.Password);
    }
);
```
and inside my handlers, I'm injecting `IOrganizationServiceAsync2`.
Sadly every time I make a request, the library must fetch wsld, so it is doing two requests:
```
https://192.168.0.10/T1/XRMServices/2011/Organization.svc?wsdl&sdkversion=9
https://192.168.0.10/T1/XRMServices/2011/Organization.svc?wsdl=wsdl0
```

In Jaeger UI, I noticed that this might take up to 3 seconds to do those two requests when the system is very busy.
So when doing 10 requests that manipulate data we have about 30 seconds extra because of those two endpoints.

**Comment by Misiu** [comment]
My approach to clone: https://github.com/Data8/DataverseClient/pull/35
