### ISSUE TITLE
Security context token expires when using currently logged on user

### ISSUE THREAD

**Issue by billeal** [Data8/DataverseClient#40]
Hello and thank you for this package.

I am using this DataveseClient to connect to an OnPremise CRM from a custom .net Core 6 web server. The service authenticates as the currently logged on user and after booting up the service everything works fine. 

After a short time the token expires and all further calls return an Error 500 with the message "The security context token is expired or is not valid. The message was not processed." The error persists until the next service restart.

Is there an intended way to renew the token?

I apologize for the beginner question. It is my first time dealing with tokens and I haven't done any progress after days of searching the web and trying to implement the AcquireTokenInteractive-method from the [Microsoft documentation](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/authenticate-oauth). I am running out of ideas and would greatly appreciate any help.

Thank you very much in advance
Alex

**Comment by MarkMpn** [comment]
Can you please post the full call stack of the exception?

**Comment by billeal** [comment]
After debugging for a while we found that the error appears only when calling the CRM via the load balancer url. Directly calling (any) frontend CRM server doesn't produce an error.

It also had nothing to do with the token expiring. Sometimes the error appeared, sometimes not, independent of run duration.

The issue is somewhere else, sorry for the inconvenience.
