### ISSUE TITLE
Support Net8

### ISSUE THREAD

**Issue by sferhah** [Data8/DataverseClient#41]
When migrating to net8, instantiation of the OnPremiseClient class results in: 

Could not load type 'System.IdentityModel.Tokens.SecurityKeyType' from assembly 'System.ServiceModel.Security, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

**Comment by MarkMpn** [comment]
I've built a simple test app on .NET 8 and I can run this library without any changes. Can you share a simple sample project to help me reproduce the error?

**Comment by sferhah** [comment]
My bad, you are right it has nothing to do with .Net 8, but with package incompatibilities: I've migrated to .net 8 and updated all packages at the same time, hence the confusion.

I narrowed my complex solution to a single project in order to identify the incompatibility:

Here's what works:
	<ItemGroup>
		<PackageReference Include="System.ServiceModel.Http" Version="4.10.3" />
		<PackageReference Include="System.ServiceModel.Security" Version="4.10.3" />
		<PackageReference Include="Data8.PowerPlatform.Dataverse.Client" Version="2.4.1" />
	</ItemGroup>

If I update System.ServiceModel.Http && System.ServiceModel.Security to their latest nuget version:

	<ItemGroup>
		<PackageReference Include="System.ServiceModel.Http" Version="6.2.0" />
		<PackageReference Include="System.ServiceModel.Security" Version="6.0.0" />
		<PackageReference Include="Data8.PowerPlatform.Dataverse.Client" Version="2.4.1" />
	</ItemGroup>

It then fails to load System.IdentityModel.Tokens.SecurityKeyType.

**Comment by MarkMpn** [comment]
It seems you're updating some packages but not all. If you also update System.ServiceModel.Federation to 6.2.0 this should resolve the problem.

**Comment by sferhah** [comment]
Excellent, adding the System.ServiceModel.Federation package to my narrowed project solves the problem!

	<ItemGroup>
		<PackageReference Include="System.ServiceModel.Federation" Version="6.2.0" />
		<PackageReference Include="System.ServiceModel.Http" Version="6.2.0" />
		<PackageReference Include="System.ServiceModel.Security" Version="6.0.0" />
		<PackageReference Include="Data8.PowerPlatform.Dataverse.Client" Version="2.4.1" />
	</ItemGroup>
