### ISSUE TITLE
Invalid Operation Exception when wsdl service contains more than one port

### ISSUE THREAD

**Issue by chrisryanhill** [Data8/DataverseClient#6]
OnPremiseClient ctor throws a System.InvalidOperationException 'Sequence contains more than one element' at .Single() when a wsdl service contains more than one port.

**Comment by MarkMpn** [comment]
Could you share how you've got CRM set up so that it has more than one port listed in the wsdl so I can reproduce this please?

**Comment by chrisryanhill** [comment]
Given CRM is hosted in IIS, the following binding should reproduce the setup.
![image](https://user-images.githubusercontent.com/8312425/159942001-8bf13cf2-18b3-441c-8c89-9d46d965d4c4.png)

Appears in line with pull request #5
