### ISSUE TITLE
On-premise: Enable server caching

### ISSUE THREAD

**Issue by sferhah** [Data8/DataverseClient#9]
The current implementation disables server caching by systematically sending the http header "Cache-Control: no-cache, max-age=0".

Is it possible to inject a custom HttpClient with NoCache to false?

I have posted an issue [https://github.com/microsoft/PowerPlatform-DataverseServiceClient/issues/260] but they only target the cloud version.

**Comment by MarkMpn** [comment]
As far as I'm aware, the on-prem server doesn't support any sort of caching based on these headers, same as Dataverse.

What different server-side behaviour would you expect to see if you could control these headers?

**Comment by sferhah** [comment]
Thanks Mark,

My diagnostic was incorrect, when I remove the header 'Cache-Control: no-cache, max-age=0' I still get slow response times compared to when I use the full .net library. I must have messed up with something during the port.

You may close the issue and thanks again for the explanation.
